repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort downloader
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black downloader
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 downloader
        language: system
        types: [python]
        pass_filenames: false
      
      - id: mypy
        name: mypy
        entry: mypy downloader
        language: system
        types: [python]
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: pylint downloader
        language: system
        types: [python]
        pass_filenames: false

      # - id: pytest
      #   name: pytest
      #   entry: python -m pytest -s downloader/tests
      #   language: system
      #   types: [python]
      #   pass_filenames: false
        
      # - id: pytest-cov
      #   name: pytest-cov
      #   entry: pytest --cov=downloader
      #   language: system
      #   types: [python]
      #   pass_filenames: false

